"""Add audit model

Revision ID: 33247aa65223
Revises: 51827df2f207
Create Date: 2026-09-08 15:34:22.298931

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33247aa65223"
down_revision: str | Sequence[str] | None = "51827df2f207"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("event_version", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("correlation_id", sa.String(), nullable=False),
        sa.Column("action_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("agent_id", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("tool_id", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=True),
        sa.Column("resource", sa.String(), nullable=True),
        sa.Column("environment", sa.String(), nullable=True),
        sa.Column("final_decision", sa.String(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_audit_events_action_id"), "audit_events", ["action_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_agent_id"), "audit_events", ["agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_correlation_id"),
        "audit_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_event_id"), "audit_events", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_final_decision"),
        "audit_events",
        ["final_decision"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_events_session_id"), "audit_events", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_timestamp"), "audit_events", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_timestamp"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_session_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_final_decision"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_correlation_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_agent_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
