"""add_approval_models

Revision ID: 51827df2f207
Revises: b52e3310d355
Create Date: 2026-09-08 04:21:04.986412

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '51827df2f207'
down_revision: str | Sequence[str] | None = 'b52e3310d355'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approver',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approver_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approver_approver_id'), 'approver', ['approver_id'], unique=True)
    op.create_table('approval_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.String(length=255), nullable=False),
    sa.Column('action_id', sa.String(length=255), nullable=False),
    sa.Column('action_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=True),
    sa.Column('resource', sa.String(length=1024), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', 'EXPIRED', 'CANCELLED', name='approvalstatusdb'), nullable=False),
    sa.Column('required_approver_role', sa.String(length=255), nullable=True),
    sa.Column('approver_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('highest_threat_severity', sa.String(length=50), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_request_action_id'), 'approval_request', ['action_id'], unique=False)
    op.create_index(op.f('ix_approval_request_approval_request_id'), 'approval_request', ['approval_request_id'], unique=True)
    op.create_index(op.f('ix_approval_request_correlation_id'), 'approval_request', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_correlation_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_approval_request_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_action_id'), table_name='approval_request')
    op.drop_table('approval_request')
    op.drop_index(op.f('ix_approver_approver_id'), table_name='approver')
    op.drop_table('approver')
    # ### end Alembic commands ###
