"""add_user_agent_delegation

Revision ID: b52e3310d355
Revises: 4c9563d5f4ad
Create Date: 2026-09-07 01:38:57.100480

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b52e3310d355"
down_revision: str | Sequence[str] | None = "4c9563d5f4ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_agent_delegation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("agent_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agent.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "agent_id", name="uix_user_agent_delegation"),
    )
    op.create_index(
        op.f("ix_user_agent_delegation_agent_id"),
        "user_agent_delegation",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_agent_delegation_user_id"),
        "user_agent_delegation",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_agent_delegation_user_id"), table_name="user_agent_delegation"
    )
    op.drop_index(
        op.f("ix_user_agent_delegation_agent_id"), table_name="user_agent_delegation"
    )
    op.drop_table("user_agent_delegation")
    # ### end Alembic commands ###
